Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere









# Section A *(2 Marks each)*

## NumPy (Numerical Python)

### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [ ]:
import numpy as np

In [ ]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it
list1=[1,2,3,4,5]
np1=np.array(list1)
print(np1)

# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
arr1=[[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]
arr = np.array(arr1)

print(arr)

[1 2 3 4 5]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
# Write a NumPy function to create an array with random values of shape [3,4]
np3=np.random.rand(3,4)

# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
np4=np.zeros((3,4))

# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
np5=np.full((3,4),1)


In [ ]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
# Hint : Use np.arange or np.linspace
np6=np.arange(0,10,2)
print(np6)

[0 2 4 6 8]


### Basic array operations
- algebraic operations
- logical operations

In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
add=np.add(a,b)
sub=np.subtract(a,b)
mult=np.multiply(a,b)
div=np.divide(a,b)

In [ ]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
suma=np.sum(a,axis=0)


# Write a NumPy function to get the sum of the array 'a' along axis=1
sumar=np.sum(a,axis=1)


In [ ]:
# Write a NumPy function to reverse the array 'a'
fa=np.flip(a)

# Write a NumPy function to reverse the array 'a' along axis=0
fa0=np.flip(a,axis=0)

# Write a NumPy function to reverse the array 'a' along axis=1
fa1=np.flip(a,axis=1)


### Sorting and concatenation
- sort arrays
- join multiple arrays


In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to sort the array 'a'
fas=np.sort(a)

# Write a NumPy function to sort the array 'a' along axis=0
fas0=np.sort(a,axis=0)

# Write a NumPy function to sort the array 'a' along axis=1
fas1=np.sort(a,axis=1)

# Write a NumPy function to sort the array 'a' in descending order along axis=0
fasrev=np.sort(a,axis=0)[::-1]


In [ ]:
# Write a NumPy function to argsort the array along axis=0
arga0=np.argsort(a,axis=0)

# Write a NumPy function to argsort the array along axis=1
arga1=np.argsort(a,axis=1)

In [ ]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
con=np.concatenate(a,b)

# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
con1=np.concatenate((a,b),axis=0)

# Note: You can do the same function using stacking, discover and try that :)


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [ ]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to get the Number of dimensions
dima=a.ndim

# Write a NumPy function to get the Shape of the array
shapea=a.shape

# Write a NumPy function to get the Size of the array
sizea=a.size


In [ ]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
reshaped = a.reshape((1,9))

In [ ]:
# Write a NumPy function to add a new axis to the array 'a'
arr_3D = a[np.newaxis, np.newaxis, np.newaxis]
arreshape= np.expand_dims(a, axis=1).shape
# Note : Show atleast two different ways of doing this


### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range
index1=a([0][0][1])
indextup = (1, 2)
slice2=a[indextup]

slice3=a([0:1,0:1,1:3])


In [ ]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
gr=(a[a>4])

# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
out=(a([a>4]&(a%2==0)))

### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
copy=np.copy(a)
copy=copy+1
print(copy)

[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [ ]:
import pandas as pd

#### Basic Data Analysis

In [ ]:
# Write a Pandas function to drop rows that contain a missing value.

data = pd.DataFrame(iris_2d)
newdf = data.dropna()

In [ ]:
# Write a Pandas function to find the correlation between the first two columns.
dfcor=data[0].corr(data[1])

In [ ]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
mean=data[3].mean()
med=data[3].median()
std=data[3].std()

In [ ]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column
iris_2d = np.expand_dims(iris_2d, axis = 0)
data[4] = (np.pi * data['petallength'] * (data['sepal_length']**2))/3


KeyError: 'petal_length'

# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [ ]:
X=np.ones((4), dtype=np.int64)

Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [ ]:
result = np.split(x, 4,2,3)

Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [ ]:
np3=np.random.rand(0,10,(2,5))

### Pandas

Run the following load command and solve the following questions

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [ ]:
df=pd.Dataframe(iris)
n = len(pd.unique(df['species']))

# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [ ]:
bins = [0, 3, 5, float('inf')]
labels = ['small', 'medium', 'large']
petal_length_bin = pd.cut(iris_2d.iloc[:, 2], bins=bins, labels=labels, right=False)

Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [ ]:
frequent_values = df['petallength'].mode()