<a href="https://colab.research.google.com/github/Abhishek-Parth/AI-foundations-ICG/blob/main/240039_Abhishek_assign0_A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere









# Section A *(2 Marks each)*

## NumPy (Numerical Python)

### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [11]:
import numpy as np
import pandas as pd

In [12]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it
l1=[1,2,3,4,5]
ar=np.array(l1)
print(ar)
# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
ar=np.arange(9)
ar=ar.reshape(3,3)
print(ar)

[1 2 3 4 5]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
# Write a NumPy function to create an array with random values of shape [3,4]
ar=np.random.randint(100,size=(3,4))
print(ar)
# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
ar=np.zeros((3,4))
print(ar)
# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
ar=np.ones((3,4))
print(ar)

[[87 18 73 52]
 [37 32 25 63]
 [52 92 61 82]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [26]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
# Hint : Use np.arange or np.linspace
ar=np.linspace(1,10,10)
print(ar)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


### Basic array operations
- algebraic operations
- logical operations

In [16]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [17]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
c=a+b
print(c)
c=a-b
print(c)
c=a*b
print(c)
c=a/b
print(c)

[[ 7 22 26]
 [99 40 82]
 [62 56 80]]
[[-15 -10 -10]
 [-81 -34 -80]
 [-60 -40 -70]]
[[-44  96 144]
 [810 111  81]
 [ 61 384 375]]
[[-0.36363636  0.375       0.44444444]
 [ 0.1         0.08108108  0.01234568]
 [ 0.01639344  0.16666667  0.06666667]]


In [24]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
sum_axis_0 = np.sum(a, axis=0)
print(sum_axis_0)
# Write a NumPy function to get the sum of the array 'a' along axis=1
sum_axis_1 = np.sum(a, axis=1)
print(sum_axis_1)

[ 6 17 14]
[10 13 14]


In [25]:
# Write a NumPy function to reverse the array 'a'
def reverse_array(arr):
  return np.flip(arr)
reversed_a = reverse_array(a)
print("Reversed array 'a':\n", reversed_a)
# Write a NumPy function to reverse the array 'a' along axis=0
def reverse_axis0(arr):
  return np.flip(arr, axis=0)
reversed_axis0_a = reverse_axis0(a)
print("\nReversed array 'a' along axis=0:\n", reversed_axis0_a)
# Write a NumPy function to reverse the array 'a' along axis=1
def reverse_axis1(arr):
  return np.flip(arr, axis=1)
reversed_axis1_a = reverse_axis1(a)
print("\nReversed array 'a' along axis=1:\n", reversed_axis1_a)

Reversed array 'a':
 [[ 5  8  1]
 [ 1  3  9]
 [ 8  6 -4]]

Reversed array 'a' along axis=0:
 [[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]]

Reversed array 'a' along axis=1:
 [[ 8  6 -4]
 [ 1  3  9]
 [ 5  8  1]]


### Sorting and concatenation
- sort arrays
- join multiple arrays


In [27]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [31]:
# Write a NumPy function to sort the array 'a'
def sort_array(arr):
    return np.sort(arr)
ar=sort_array(a)
print(ar)
# Write a NumPy function to sort the array 'a' along axis=0
def sort_axis0(arr):
    return np.sort(arr, axis=0)
ar=sort_axis0(a)
print(ar)
# Write a NumPy function to sort the array 'a' along axis=1
def sort_axis1(arrr):
    return np.sort(arrr, axis=0)
ar=sort_axis1(a)
print(ar)
# Write a NumPy function to sort the array 'a' in descending order along axis=0
def sort_de_axis0(arr):
    sorted_arr = np.sort(arr, axis=0)
    return np.flip(sorted_arr, axis=0)
print(sort_de_axis0(a))

[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[-4  3  8]
 [ 1  5  8]
 [ 1  6  9]]
[[-4  3  8]
 [ 1  5  8]
 [ 1  6  9]]
[[ 1  6  9]
 [ 1  5  8]
 [-4  3  8]]


In [35]:
# Write a NumPy function to argsort the array along axis=0
def argsort_axis0(arr):
  return np.argsort(arr, axis=0)
print(argsort_axis0(a))
# Write a NumPy function to argsort the array along axis=1
def argsort_axis1(arr):
  return np.argsort(arr, axis=1)
print(argsort_axis1(a))

[[0 1 0]
 [1 2 2]
 [2 0 1]]
[[0 1 2]
 [0 1 2]
 [0 1 2]]


In [36]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
def concatenate_arrays(arr1, arr2):
  return np.concatenate((arr1, arr2))
print(concatenate_arrays(a,b))
# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
def concatenate_axis0(arr1, arr2):
  return np.concatenate((arr1, arr2), axis=0)
print(concatenate_axis0(a,b))
# Note: You can do the same function using stacking, discover and try that :)
def stack_arrays(arr1, arr2):
  return np.stack((arr1, arr2))
print(stack_arrays(a,b))

[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[[-4  6  8]
  [ 1  3  9]
  [ 1  5  8]]

 [[11 16 18]
  [90 37 81]
  [61 48 75]]]


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [37]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [38]:
# Write a NumPy function to get the Number of dimensions
def get_dimensions(arr):
  return arr.ndim
dimensions = get_dimensions(a)
print(dimensions)
# Write a NumPy function to get the Shape of the array
def get_shape(arr):
  return arr.shape
shape = get_shape(a)
print(shape)
# Write a NumPy function to get the Size of the array
def get_size(arr):
  return arr.size
s = get_size(a)
print(s)

2
(3, 3)
9


In [39]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
def reshape_array(arr):
  return arr.reshape(1, 9)
f = reshape_array(a)
print(f)

[[4 6 8 9 3 1 1 8 5]]


In [41]:
# Write a NumPy function to add a new axis to the array 'a'
# Note : Show atleast two different ways of doing this
def add_new_axis1(arr):
    new_arr1 = arr[:, np.newaxis]
    return new_arr1
n=add_new_axis1(a)
print(n)
def add_new_axis2(ar):
    new=ar[:, np.newaxis]
    return new
nn=add_new_axis2(a)
print(nn)

[[[4 6 8]]

 [[9 3 1]]

 [[1 8 5]]]
[[[4 6 8]]

 [[9 3 1]]

 [[1 8 5]]]


### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [42]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [43]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range
def index_and_slice(arr):
    integer_indexed = arr[1]
    print("Indexing by an integer:", integer_indexed)

    tuple_indexed = arr[1, 2]
    print("Indexing by a tuple:", tuple_indexed)

    range_indexed = arr[0:2, 1:3]
    print("Using range:", range_indexed)

index_and_slice(a)

Indexing by an integer: [0 3 1]
Indexing by a tuple: 1
Using range: [[6 0]
 [3 1]]


In [45]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
def greater_than_4(arr):
  return arr[arr > 4]
print(greater_than_4(a))
# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
def greater_4_and_divisible_2(arr):
  return arr[(arr > 4) & (arr % 2 == 0)]
print(greater_4_and_divisible_2(a))

[6 8 5]
[6 8]


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [46]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [47]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
def c_and_i(arr):
  arr_copy = arr.copy()
  arr_copy += 1
  return arr_copy
incre_a = c_and_i(a)
print(incre_a)

[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [48]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [50]:
# Write a Pandas function to drop rows that contain a missing value.
#print(iris_2d)
def drop_miss_value(arr):
    df=pd.DataFrame(arr)
    return df.dropna()
dff=drop_miss_value(iris_2d)
print(dff.to_string)


<bound method DataFrame.to_string of        0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]>


In [51]:
# Write a Pandas function to find the correlation between the first two columns.
def corr(arr):
    df=pd.DataFrame(arr)
    return df.corr()
print(corr(iris_2d))

          0         1         2         3
0  1.000000 -0.109369  0.871754  0.817954
1 -0.109369  1.000000 -0.420516 -0.356544
2  0.871754 -0.420516  1.000000  0.962757
3  0.817954 -0.356544  0.962757  1.000000


In [52]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
def mean_median_std(arr):
    df=pd.DataFrame(arr)
    return df.describe()
print(mean_median_std(iris_2d))

                0           1           2           3
count  150.000000  150.000000  150.000000  150.000000
mean     5.843333    3.054000    3.758667    1.198667
std      0.828066    0.433594    1.764420    0.763161
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.350000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000


In [53]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column

# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [ ]:

x = np.arange(4, dtype=np.int64)
ones = np.ones_like(x)
print(ones)

Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [54]:
x = np.arange(1, 10)
ar1=x[0:4]
ar2=x[4:6]
ar3=x[6:9]
print(ar1)
print(ar2)
print(ar3)

[1 2 3 4]
[5 6]
[7 8 9]


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [55]:
x=np.random.randint(10, size=(2,5))
print(x)
print("max_value ",x.max(axis=1),"index ",x.argmax(axis=1))
print("min_value ",x.min(axis=1),"index ",x.argmin(axis=1))

[[0 3 8 7 1]
 [8 3 0 6 9]]
max_value  [8 9] index  [2 4]
min_value  [0 0] index  [0 2]


### Pandas

Run the following load command and solve the following questions

In [56]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [64]:
def unique_species(arr):
    df=pd.DataFrame(arr)
    return df[4].nunique()
print(unique_species(iris))

          0       1       2       3                  4
0    b'5.1'  b'3.5'  b'1.4'  b'0.2'     b'Iris-setosa'
1    b'4.9'  b'3.0'  b'1.4'  b'0.2'     b'Iris-setosa'
2    b'4.7'  b'3.2'  b'1.3'  b'0.2'     b'Iris-setosa'
3    b'4.6'  b'3.1'  b'1.5'  b'0.2'     b'Iris-setosa'
4    b'5.0'  b'3.6'  b'1.4'  b'0.2'     b'Iris-setosa'
..      ...     ...     ...     ...                ...
145  b'6.7'  b'3.0'  b'5.2'  b'2.3'  b'Iris-virginica'
146  b'6.3'  b'2.5'  b'5.0'  b'1.9'  b'Iris-virginica'
147  b'6.5'  b'3.0'  b'5.2'  b'2.0'  b'Iris-virginica'
148  b'6.2'  b'3.4'  b'5.4'  b'2.3'  b'Iris-virginica'
149  b'5.9'  b'3.0'  b'5.1'  b'1.8'  b'Iris-virginica'

[150 rows x 5 columns]


# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [62]:
def most_frequent_petal_length(arr):
    df=pd.DataFrame(arr)
    h=df[2].mode()
    return h
print(most_frequent_petal_length(iris))

0    b'1.5'
Name: 2, dtype: object
