Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere









# Section A *(2 Marks each)*

## NumPy (Numerical Python)

### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [2]:
import numpy as np

In [2]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it
arr=np.array([1,2,3,4,5])
print(arr)
# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
# Write a NumPy function to create an array with random values of shape [3,4]
arr=np.random.rand(3,4)
print(arr)
# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
arr=np.zeros([3,4])
print(arr)
# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
arr=np.full((3,4),1)
print(arr)

[[0.1549189  0.8115381  0.31731882 0.6346099 ]
 [0.53295221 0.0373429  0.07624782 0.48569989]
 [0.47289683 0.10177482 0.46562988 0.65053587]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [4]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
# Hint : Use np.arange or np.linspace
arr=np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


### Basic array operations
- algebraic operations
- logical operations

In [5]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [6]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
sum=np.add(a,b)
print(sum)
diff=np.subtract(a,b)
print(diff)
prod=np.multiply(a,b)
print(prod)
division=np.divide(a,b)
print(division)

[[ 7 22 26]
 [99 40 82]
 [62 56 80]]
[[-15 -10 -10]
 [-81 -34 -80]
 [-60 -40 -70]]
[[-44  96 144]
 [810 111  81]
 [ 61 384 375]]
[[-0.36363636  0.375       0.44444444]
 [ 0.1         0.08108108  0.01234568]
 [ 0.01639344  0.16666667  0.06666667]]


In [7]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
print(np.sum(a,axis=0))
# Write a NumPy function to get the sum of the array 'a' along axis=1
print(np.sum(b,axis=1))

[ 6 17 14]
[ 45 208 184]


In [8]:
# Write a NumPy function to reverse the array 'a'
c=a[::-1]
print(c)
# Write a NumPy function to reverse the array 'a' along axis=0
c=np.flip(a,axis=0)
print(c)
# Write a NumPy function to reverse the array 'a' along axis=1
c=np.flip(a,axis=1)
print(c)

[[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]]
[[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]]
[[ 8  6 -4]
 [ 1  3  9]
 [ 5  8  1]]


### Sorting and concatenation
- sort arrays
- join multiple arrays


In [9]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [10]:
# Write a NumPy function to sort the array 'a'
c=np.sort(a)
print(c)
# Write a NumPy function to sort the array 'a' along axis=0
c=np.sort(a)
print(c)
# Write a NumPy function to sort the array 'a' along axis=1
c=np.sort(a,axis=1)
print(c)
# Write a NumPy function to sort the array 'a' in descending order along axis=0
c=np.flip(a,axis=0)

[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]


In [11]:
# Write a NumPy function to argsort the array along axis=0
c=np.argsort(a)
# Write a NumPy function to argsort the array along axis=1
c=np.argsort(a,axis=1)

In [12]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
c=np.concatenate((a,b))
print(c)
# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
c=np.concatenate((a,b),axis=0)
print(c)
# Note: You can do the same function using stacking, discover and try that :)
#**************************************
print(c)

[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [13]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [14]:
# Write a NumPy function to get the Number of dimensions
print(np.ndim(a))
# Write a NumPy function to get the Shape of the array
print(np.shape(a))
# Write a NumPy function to get the Size of the array
print(np.size(a))

2
(3, 3)
9


In [15]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
print(np.reshape(a,(1,9)))

[[4 6 8 9 3 1 1 8 5]]


In [17]:
# Write a NumPy function to add a new axis to the array 'a'
# Note : Show atleast two different ways of doing this
print(np.expand_dims(a,0))
print(np.expand_dims(a,1))

[[[4 6 8]
  [9 3 1]
  [1 8 5]]]
[[[4 6 8]]

 [[9 3 1]]

 [[1 8 5]]]


### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [4]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range


In [13]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
print(a[np.where(a>4)])
# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
print(a[(a>4)&(a%2==0)])

[6 8 5]
[6 8]


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [14]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
a_copy=a.copy()
a_copy+=1
print(a_copy)

## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [15]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [49]:
# Write a Pandas function to drop rows that contain a missing value.
import pandas as pd
data=pd.DataFrame(iris_2d)
data=data.dropna()
data.head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [18]:
# Write a Pandas function to find the correlation between the first two columns.
print(data.loc[0].corr(data.loc[1]))

0.9959986612402598


In [20]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
print(data[3].mean())
print(data[3].std())
print(data[3].median())

1.1986666666666668
0.7631607417008414
1.3


In [50]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
import math
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column
data['Volume'] = (math.pi * data[0] ** 2 * data[2]) / 3

# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [24]:
print(np.ones(4))

[1. 1. 1. 1.]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [27]:
x=np.array([1,2,3,4,5,6,7,8,9])
y=x[0:4]
z=x[4:6]
a=x[6:9]

Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [ ]:
x = np.random.randint(0, 10, size=(2, 5))

# Get the maximum values and their indices along the second axis (axis=1)
max_values = np.max(x, axis=1)
min_values = np.min(x, axis=1)

### Pandas

Run the following load command and solve the following questions

In [28]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [37]:
data=pd.DataFrame(iris)
data[4].nunique()

3

# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [51]:
data['length'] = 0
data.loc[data[2] > 5, 'length'] = 'large'
data.loc[(data[2] <= 5) & (data[2] >= 3), 'length'] = 'medium'
data.loc[data[2] < 3, 'length'] = 'small'
print(data['length'])

0       small
1       small
2       small
3       small
4       small
        ...  
145     large
146    medium
147     large
148     large
149     large
Name: length, Length: 150, dtype: object


<ipython-input-51-c6f9023ef979>:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'large' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[data[2] > 5, 'length'] = 'large'


Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [41]:
data[2].mode()

0    b'1.5'
Name: 2, dtype: object