Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere









# Section A *(2 Marks each)*

## NumPy (Numerical Python)

### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [6]:
import numpy as np

In [5]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it
numpy_array=np.array([1,2,3,4,5])
print(numpy_array)

# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
numpy_2d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(numpy_2d_array)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
# Write a NumPy function to create an array with random values of shape [3,4]
array=np.random.rand(3,4)
print(array)
# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
def array1(shape):
  return np.zeros(shape)
zarray=array1((3,4))
print(zarray)
# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
def array2(shape):
  return np.ones(shape)
oarray=array2((3,4))
print(oarray)

[[0.06009979 0.58489765 0.12031384 0.51888852]
 [0.39876938 0.42502114 0.59782417 0.18720031]
 [0.59775444 0.69823323 0.77331989 0.41057734]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [21]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
# Hint : Use np.arange or np.linspace
array=np.linspace(2,16,8)
print(array)

[ 2.  4.  6.  8. 10. 12. 14. 16.]


### Basic array operations
- algebraic operations
- logical operations

In [23]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [28]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
c=a+b
print(c)
d=a-b
print(d)
e=a*b
print(e)
f=a/b
print(f)

[[ 7 22 26]
 [99 40 82]
 [62 56 80]]
[[-15 -10 -10]
 [-81 -34 -80]
 [-60 -40 -70]]
[[-44  96 144]
 [810 111  81]
 [ 61 384 375]]
[[-0.36363636  0.375       0.44444444]
 [ 0.1         0.08108108  0.01234568]
 [ 0.01639344  0.16666667  0.06666667]]


In [30]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
print(np.sum(a,axis=0))
# Write a NumPy function to get the sum of the array 'a' along axis=1
print(np.sum(a,axis=1))

[ 6 17 14]
[10 13 14]


In [33]:
# Write a NumPy function to reverse the array 'a'
print(a[::-1])
# Write a NumPy function to reverse the array 'a' along axis=0
print(a[::-1,:])
# Write a NumPy function to reverse the array 'a' along axis=1
print(a[:,::-1])

[[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]]
[[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]]
[[ 8  6 -4]
 [ 1  3  9]
 [ 5  8  1]]


### Sorting and concatenation
- sort arrays
- join multiple arrays


In [43]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [37]:
# Write a NumPy function to sort the array 'a'
print(np.sort(a))
# Write a NumPy function to sort the array 'a' along axis=0
c=np.sort(a,axis=0)
print(c)
# Write a NumPy function to sort the array 'a' along axis=1
print(np.sort(a,axis=1))
# Write a NumPy function to sort the array 'a' in descending order along axis=0
d=c[::-1]
print(d)

[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[-4  3  1]
 [ 1  6  5]
 [ 9  8  8]]
[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[ 9  8  8]
 [ 1  6  5]
 [-4  3  1]]


In [40]:
# Write a NumPy function to argsort the array along axis=0
print(np.argsort(a,axis=0))
# Write a NumPy function to argsort the array along axis=1
print(np.argsort(a,axis=1))

[[0 1 1]
 [2 0 2]
 [1 2 0]]
[[0 1 2]
 [2 1 0]
 [0 2 1]]


In [45]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
print(np.concatenate((a,b)))
# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
print(np.concatenate((a,b),axis=0))
# Note: You can do the same function using stacking, discover and try that :)


[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [46]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [49]:
# Write a NumPy function to get the Number of dimensions
print(np.ndim(a))
# Write a NumPy function to get the Shape of the array
print(np.shape(a))
# Write a NumPy function to get the Size of the array
print(np.size(a))

2
(3, 3)
9


In [50]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
print(np.reshape(a,(1,9)))

[[4 6 8 9 3 1 1 8 5]]


In [53]:
# Write a NumPy function to add a new axis to the array 'a'
# Note : Show atleast two different ways of doing this
print(a[:,np.newaxis])
print(np.expand_dims(a,axis=0))

[[[4 6 8]]

 [[9 3 1]]

 [[1 8 5]]]
[[[4 6 8]
  [9 3 1]
  [1 8 5]]]


### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [54]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range


In [65]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
print(a[a>4])
# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
print(a[(a>4)&(a%2==0)])

[6 8 5]
[6 8]


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [56]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [55]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
b=a.copy()
b+=1
print(b)

[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [66]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [71]:
import pandas as pd
df = pd.DataFrame(iris_2d)
df.head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [72]:
# Write a Pandas function to drop rows that contain a missing value.
df.dropna()

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [73]:
# Write a Pandas function to find the correlation between the first two columns.
df[0].corr(df[1])

-0.10936924995064937

In [75]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
print(df[2].mean())
print(df[2].median())
print(df[2].std())

1.7644204199522617

In [ ]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column
df[3]=(df[0]*df[1])+df[2]
df[3] = (3.14 * df[0] * (df[1] * df[1]))/3
df.head()

# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [68]:
import numpy as np
x = np.arange(4, dtype=np.int64)
y=np.ones_like(x)
print(y)

[1 1 1 1]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [76]:
import numpy as np

x = np.arange(1, 10)

x1 = x[:4]
x2 = x[4:6]
x3 = x[6:]

print(x1)
print(x2)
print(x3)

[1 2 3 4]
[5 6]
[7 8 9]


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [ ]:
import numpy as np
x = np.random.randint(0, 10, size=(2, 5))
max_values = np.max(x, axis=1)
min_values = np.min(x, axis=1)
max_indices = np.argmax(x, axis=1)
min_indices = np.argmin(x, axis=1)
print("Array x:")
print(x)
print("\nMaximum values:", max_values)
print("Minimum values:", min_values)
print("\nIndices of maximum values:", max_indices)
print("Indices of minimum values:", min_indices)

### Pandas

Run the following load command and solve the following questions

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [ ]:
import pandas as pd
import numpy as np

def bin_petal_length(iris_2d):
  petal_length = iris_2d[:, 2]
  bins = pd.cut(petal_length, bins=[0, 3, 5, np.inf], labels=['small', 'medium', 'large'])
  return bins
iris_df = pd.DataFrame(iris_2d, columns=['sepal_length', 'sepal_width', 'petal_length', 'petal_width'])
iris_df['petal_length_binned'] = bin_petal_length(iris_2d)
print(iris_df)

Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [ ]:
import pandas as pd
import numpy as np

def most_frequent_petal_length(iris_2d):
  petal_length = iris_2d[:, 2]
  petal_length_counts = pd.Series(petal_length).value_counts()
  most_frequent_length = petal_length_counts.idxmax()
  return most_frequent_length
most_frequent = most_frequent_petal_length(iris_2d)
print("The most frequent petal length is:", most_frequent)