Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere









# Section A *(2 Marks each)*

## NumPy (Numerical Python)

### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [ ]:
import numpy as np

In [ ]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it
myvar= np.array([1,2,3,4,5])
print(myvar)

# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
my_var=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(my_var)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Write a NumPy function to create an array with random values of shape [3,4]
myva=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(myva)

# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
myvae=np.array([[0,0,0,0],[0,0,0,0],[0,0,0,0]])
print(myvae)
# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
myvab=np.array([[1,1,1,1],[1,1,1,1],[1,1,1,1]])
print(myvab)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
myvaw=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(myvaw[::2])
# Hint : Use np.arange or np.linspace

[ 1  3  5  7  9 11]


### Basic array operations
- algebraic operations
- logical operations

In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[ 7 22 26]
 [99 40 82]
 [62 56 80]]
[[-15 -10 -10]
 [-81 -34 -80]
 [-60 -40 -70]]
[[-44  96 144]
 [810 111  81]
 [ 61 384 375]]
[[-0.36363636  0.375       0.44444444]
 [ 0.1         0.08108108  0.01234568]
 [ 0.01639344  0.16666667  0.06666667]]


In [ ]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
print(np.sum(a,axis=0))
# Write a NumPy function to get the sum of the array 'a' along axis=1
print(np.sum(a,axis=1))

[ 6 17 14]
[10 13 14]


In [ ]:
# Write a NumPy function to reverse the array 'a'
print(np.flip(a))
# Write a NumPy function to reverse the array 'a' along axis=0
print(np.flip(a,axis=0))
# Write a NumPy function to reverse the array 'a' along axis=1
print(np.flip(a,axis=1))

[[ 5  8  1]
 [ 1  3  9]
 [ 8  6 -4]]
[[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]]
[[ 8  6 -4]
 [ 1  3  9]
 [ 5  8  1]]


### Sorting and concatenation
- sort arrays
- join multiple arrays


In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to sort the array 'a'
print(np.sort(a))
# Write a NumPy function to sort the array 'a' along axis=0
c=np.sort((a),axis=0)
print(c)
# Write a NumPy function to sort the array 'a' along axis=1
print(np.sort((a),axis=1))
# Write a NumPy function to sort the array 'a' in descending order along axis=0
d=np.flip(c,axis=0)
print(d)

[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[-4  3  1]
 [ 1  6  5]
 [ 9  8  8]]
[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[ 9  8  8]
 [ 1  6  5]
 [-4  3  1]]


In [ ]:
# Write a NumPy function to argsort the array along axis=0
print(np.argsort(a,axis=0))
# Write a NumPy function to argsort the array along axis=1
print(np.argsort(a,axis=1))

[[0 1 1]
 [2 0 2]
 [1 2 0]]
[[0 1 2]
 [2 1 0]
 [0 2 1]]


In [ ]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
print(np.concatenate((a,b)))

# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
print(np.concatenate((a,b),axis=0))



g=np.stack((a,b),axis=0)
h=np.reshape((g),(6,3))
print(h)
# Note: You can do the same function using stacking, discover and try that :)


[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [ ]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to get the Number of dimensions
print(np.ndim(a))
# Write a NumPy function to get the Shape of the array
print(np.shape(a))
# Write a NumPy function to get the Size of the array
print(np.size(a))

2
(3, 3)
9


In [ ]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
print(np.reshape(a,(1,9)))

[[-4  6  8  9  3  1  1  8  5]]


In [ ]:
# Write a NumPy function to add a new axis to the array 'a'
s=np.reshape(a,(-1,3,3))
print(s)
print("""
""")

print(a[:,:,np.newaxis])
# Note : Show atleast two different ways of doing this


[[[4 6 8]
  [9 3 1]
  [1 8 5]]]


[[[4]
  [6]
  [8]]

 [[9]
  [3]
  [1]]

 [[1]
  [8]
  [5]]]


### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
print(a[2][1])

print(a[0:2])
# Show all three - indexing by a integer, indexing by a tuple, using range
print(a[2][0])
print(a[1:2,1:2])
print(a[(0,2)])

8
[[4 6 0]
 [0 3 1]]
1
[[3]]
0


In [ ]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
for x in a:
  for y in x:
    if(y>4):
      print(y)

print('''
''')
# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
for x in a:
  for y in x:
    if(y>4 and y%2==0):
      print(y)

6
8
5


6
8


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
b=np.copy(a)
print(b+1)


[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [ ]:
import pandas as pd
df=pd.read_csv(url)

#### Basic Data Analysis

In [ ]:
# Write a Pandas function to drop rows that contain a missing value.
hello=df.dropna()

In [ ]:
# Write a Pandas function to find the correlation between the first two columns.
df.iloc[:,[0,1]].corr()

5.1       3.5
5.1  1.000000 -0.103784
3.5 -0.103784  1.000000

In [ ]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
df.iloc[:,2].describe().loc[['mean','50%','std']]

mean    3.774497
50%     4.400000
std     1.759651
Name: 1.4, dtype: float64

In [ ]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
df["volume"]=(np.pi*df.iloc[:,2]*df.iloc[:,0]**2)/3
df.to_csv(url, index=False)
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column

# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [ ]:
import numpy as np

In [ ]:
t=np.array([1,1,1,1])
print(t.astype(np.int64))

[1 1 1 1]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [ ]:
x=np.array([1,2,3,4,5,6,7,8,9])
print(np.array_split(x,3))

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [ ]:
x=np.array([[7,4,8,7,2],[5,7,8,1,2]])
y=np.reshape(x,(10))
z=np.sort(y)
print(z[9])
print(z[0])
print(np.where(x==z[9]))
print(np.where(x==z[0]))

8
1
(array([0, 1]), array([2, 2]))
(array([1]), array([3]))


### Pandas

Run the following load command and solve the following questions

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [ ]:
hello=df.iloc[:,4].nunique()

# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [ ]:
hi=pd.cut(df.iloc[:,2], bins=[0,3,5,float('inf')], labels=['small','medium','large'])
print(hi)

0       small
1       small
2       small
3       small
4       small
        ...  
144     large
145    medium
146     large
147     large
148     large
Name: 1.4, Length: 149, dtype: category
Categories (3, object): ['small' < 'medium' < 'large']


*Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset*

In [ ]:
hello=df.iloc[:,2].mode()[0]
print(hello)

1.5
