Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere









# Section A *(2 Marks each)*

## NumPy (Numerical Python)

### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [3]:
import numpy as np

In [4]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it
arr=np.array([1,2,3,4,5])
print(arr)


# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
arr_2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# Write a NumPy function to create an array with random values of shape [3,4]
rndm=np.empty((3,4))


# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
zero=np.zeros((3,4))

# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
one=np.ones((3,4))


In [6]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
l_space=np.linspace(1,5,9) #creates an AP of 9 numbers from 1 to 5
print(l_space)
# Hint : Use np.arange or np.linspace

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


### Basic array operations
- algebraic operations
- logical operations

In [7]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [8]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
ad=a+b
sub=a-b
mul=a*b #here i assume that we are talking about multiplying via each element and not the standard matrix multiplication
div=a/b
#print(ad,sub,mul,div)

In [9]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
sum_arr_0=a.sum(axis=0)
# Write a NumPy function to get the sum of the array 'a' along axis=1
sum_arr_1=a.sum(axis=1)


In [10]:
# Write a NumPy function to reverse the array 'a'
rev_a=np.flip(a)
# Write a NumPy function to reverse the array 'a' along axis=0
rev_a_0=np.flip(a,axis=0)
# Write a NumPy function to reverse the array 'a' along axis=1
rev_a_1=np.flip(a,axis=1)

### Sorting and concatenation
- sort arrays
- join multiple arrays


In [11]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [12]:
# Write a NumPy function to sort the array 'a'
a_flatten=a.ravel()
sorted_a=np.sort(a_flatten)
sorted_a=sorted_a.reshape(3,3)
print(sorted_a) #i am not able to find a function that would directly sort the array like that....i hope thats what the qtn means by sorting...

# Write a NumPy function to sort the array 'a' along axis=0
sorted_a_0=np.sort(a,axis=0)
# Write a NumPy function to sort the array 'a' along axis=1
sorted_a_1=np.sort(a,axis=1)
# Write a NumPy function to sort the array 'a' in descending order along axis=0
#we will just sort normally and then assign in opposite way(i have to use net for how to code this)
des_a=np.sort(a,axis=0)[::-1,:]
print(des_a)

[[-4  1  1]
 [ 3  5  6]
 [ 8  8  9]]
[[ 9  8  8]
 [ 1  6  5]
 [-4  3  1]]


In [13]:
# Write a NumPy function to argsort the array along axis=0
argsorted_0=a.argsort(axis=0)
print(argsorted_0)
# Write a NumPy function to argsort the array along axis=1
argsorted_1=a.argsort(axis=1)
print(argsorted_1)

[[0 1 1]
 [2 0 2]
 [1 2 0]]
[[0 1 2]
 [2 1 0]
 [0 2 1]]


In [14]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
con=np.concatenate((a,b),axis=1)
print(con)
# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
con_0=np.concatenate((a,b),axis=0)
print(con_0)
# Note: You can do the same function using stacking, discover and try that :)
#done and dusted from gfg hstack vstack stack along axis

[[-4  6  8 11 16 18]
 [ 9  3  1 90 37 81]
 [ 1  8  5 61 48 75]]
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [15]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [16]:
# Write a NumPy function to get the Number of dimensions
n=a.ndim
print(n)
# Write a NumPy function to get the Shape of the array
y=a.shape
print(y)
# Write a NumPy function to get the Size of the array
z=a.size
print(z)

2
(3, 3)
9


In [17]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
new_a=a.reshape((1,9))

In [18]:
# Write a NumPy function to add a new axis to the array 'a'
y=np.expand_dims(a,axis=0)
print(y)

z=a[np.newaxis,...]
print(z)
# Note : Show atleast two different ways of doing this


[[[4 6 8]
  [9 3 1]
  [1 8 5]]]
[[[4 6 8]
  [9 3 1]
  [1 8 5]]]


### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [33]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [44]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists

# Show all three - indexing by a integer, indexing by a tuple, using range
#indexing by integer----
print(a[0])
print(a[1,2])

#indexing by a tupple
print(a[(1,2),(1,2)])

# indexing by range

print(a[0:2,1:2]) # runs rwos from 0 to 1(2 excluded) and and to 1st column only


[4 6 0]
1
[3 5]
[[6]]


In [38]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
find=np.where(a>4)
print(find)
# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
find_2=np.where((a>4)&(a%2==0))
print(find_2)


(array([0, 2, 2]), array([1, 1, 2]))
(array([0, 2]), array([1, 1]))


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [22]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [23]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
#b=np.empty_like(a) i dont know why its not working?
copy_a=a.copy()
copy_a=copy_a+1
print(copy_a)

[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [24]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [25]:
# Write a Pandas function to drop rows that contain a missing value.


In [26]:
# Write a Pandas function to find the correlation between the first two columns.


In [27]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.


In [28]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column

# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [47]:
x=np.arange(4,dtype=np.int64)
X=np.ones_like(x)
print(X)

[1 1 1 1]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [48]:
x=np.arange(9)
x=x+1
one=x[:4]
two=x[4:6]
three=x[6:9]

print(one,two,three)

[1 2 3 4] [5 6] [7 8 9]


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [56]:
x=np.random.randint(1,10,size=(2,5))#assuming 0 is exclusive too
max_x=np.max(x,axis=1)
min_x=np.min(x,axis=1)
print(x)
print(max_x,min_x)

[[1 4 4 3 8]
 [6 9 8 4 2]]
[8 9] [1 2]


### Pandas

Run the following load command and solve the following questions

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset