Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere









# Section A *(2 Marks each)*

## NumPy (Numerical Python)

### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [2]:
import numpy as np

In [ ]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it

# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it

In [ ]:
a = list((1,2,3,4,5))
arr = np.array(a)
print(arr)
# for i in arr:
#   print(i,end=" ")

1 2 3 4 5 

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Write a NumPy function to create an array with random values of shape [3,4]

# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]

# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]


In [ ]:
import random
arr = np.ones((3,4))
for i in range(3):
  for j in range(4):
    arr[i,j] = random.randrange(10)
print(arr)


[[1. 4. 1. 8.]
 [0. 4. 3. 5.]
 [2. 8. 1. 2.]]


In [ ]:
arr = np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
arr = np.ones((3,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
# Hint : Use np.arange or np.linspace

In [ ]:
arr=np.linspace(0, 12, 5)
print(arr)

[ 0.  3.  6.  9. 12.]


In [ ]:
arr = np.arange(0, 15, 3)
print(arr)

[ 0  3  6  9 12]


### Basic array operations
- algebraic operations
- logical operations

In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'

In [ ]:
def algebra(a, b):
  return {
      "SUM": np.add(a,b),
      "DIFF": np.subtract(a,b),
      "MUL": a @ b,
      "DIV": a @  np.linalg.inv(b)
  }

result = algebra(a, b)
print(f"SUM: \n{result['SUM']}\n")
print(f"DIFF: \n{result['DIFF']}\n")
print(f"MUL: \n{result['MUL']}\n")
print(f"DIV: \n{result['DIV']}\n")

SUM: 
[[ 7 22 26]
 [99 40 82]
 [62 56 80]]

DIFF: 
[[-15 -10 -10]
 [-81 -34 -80]
 [-60 -40 -70]]

MUL: 
[[ 984  542 1014]
 [ 430  303  480]
 [1036  552 1041]]

DIV: 
[[-2.49247471 -0.81174439  1.58154453]
 [ 3.30150506  0.83765112 -1.68369109]
 [ 1.3002714   0.06908463 -0.32000987]]



In [ ]:
# Write a NumPy function to get the sum of the array 'a' along axis=0

# Write a NumPy function to get the sum of the array 'a' along axis=1


In [ ]:
print(np.sum(a,axis=0))

[ 6 17 14]


In [ ]:
print(np.sum(a,axis=1))

[10 13 14]


In [ ]:
# Write a NumPy function to reverse the array 'a'

# Write a NumPy function to reverse the array 'a' along axis=0

# Write a NumPy function to reverse the array 'a' along axis=1


In [ ]:
def reverse(a):
  return np.flip(a,axis=0)

print(reverse(a))

[[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]]


In [ ]:
def reverse(a):
  return np.flip(a,axis=1)

print(reverse(a))

[[ 8  6 -4]
 [ 1  3  9]
 [ 5  8  1]]


In [ ]:
def reverse(a):
  return np.flip(a)

print(reverse(a))

[[ 5  8  1]
 [ 1  3  9]
 [ 8  6 -4]]


### Sorting and concatenation
- sort arrays
- join multiple arrays


In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to sort the array 'a'

# Write a NumPy function to sort the array 'a' along axis=0

# Write a NumPy function to sort the array 'a' along axis=1

# Write a NumPy function to sort the array 'a' in descending order along axis=0


In [ ]:
def sort(a):
  return np.sort(a)

print(sort(a))

[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]


In [ ]:
def sort(a):
  return np.sort(a,axis=0)

print(sort(a))

[[-4  3  1]
 [ 1  6  5]
 [ 9  8  8]]


In [ ]:
def sort(a):
  return np.sort(a,axis=1)

print(sort(a))

[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]


In [ ]:
def sort(a):
  sorted = np.sort(a, axis=0)
  return np.flip(sorted, axis=0)

print(sort(a))

[[ 9  8  8]
 [ 1  6  5]
 [-4  3  1]]


In [ ]:
# Write a NumPy function to argsort the array along axis=0

# Write a NumPy function to argsort the array along axis=1


In [ ]:
def argsort(a):
  return np.argsort(a,axis=0)

print(argsort(a))

[[0 1 1]
 [2 0 2]
 [1 2 0]]


In [ ]:
def argsort(a):
  return np.argsort(a,axis=1)

print(argsort(a))

[[0 1 2]
 [2 1 0]
 [0 2 1]]


In [ ]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'

# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0

# Note: You can do the same function using stacking, discover and try that :)


In [ ]:
def concatenate(a, b):
  return np.concatenate((a,b),axis=1)

print(concatenate(a, b))

[[-4  6  8 11 16 18]
 [ 9  3  1 90 37 81]
 [ 1  8  5 61 48 75]]


In [ ]:
def concatenate(a, b):
  return np.concatenate((a,b),axis=0)

print(concatenate(a, b))

[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]


In [ ]:
def concatenate(a, b):
  return np.vstack((a,b))

print(concatenate(a, b))

[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]


In [ ]:
def concatenate(a, b):
  return np.hstack((a,b))

print(concatenate(a, b))

[[-4  6  8 11 16 18]
 [ 9  3  1 90 37 81]
 [ 1  8  5 61 48 75]]


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [ ]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to get the Number of dimensions

# Write a NumPy function to get the Shape of the array

# Write a NumPy function to get the Size of the array


In [ ]:
print(a.ndim)

2


In [ ]:
print(a.shape)

(3, 3)


In [ ]:
print(a.size)

9


In [ ]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)


In [ ]:
print(a.reshape(-1))

[4 6 8 9 3 1 1 8 5]


In [ ]:
# Write a NumPy function to add a new axis to the array 'a'
# Note : Show atleast two different ways of doing this


In [ ]:
print(np.expand_dims(a,axis=0))

[[[4 6 8]
  [9 3 1]
  [1 8 5]]]


In [ ]:
print(np.expand_dims(a,axis=1))

[[[4 6 8]]

 [[9 3 1]]

 [[1 8 5]]]


### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range


In [ ]:
print(a[2,1])

8


In [ ]:
print(a[(2,1)])

8


In [ ]:
print(a[2:3,1:2])

[[8]]


In [ ]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4

# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2


In [ ]:
def selection(arr):
    greater_than_4 = arr > 4

    selected_values = arr[greater_than_4]

    return selected_values

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
selection(arr)

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
def selection(arr):
    greater_than_4 = arr > 4
    divisible_by_2 = arr % 2 == 0

    selected_values = arr[greater_than_4 & divisible_by_2]

    return selected_values

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
selection(arr)

array([ 6,  8, 10])

### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1


In [ ]:
b = np.copy(a)
b= b+1
print(b)

[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [3]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [ ]:
# Write a Pandas function to drop rows that contain a missing value.


In [5]:
import pandas as pd

In [11]:
df = pd.DataFrame(iris_2d)
new_df = df.dropna()

print(new_df.to_string())

       0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
5    5.4  3.9  1.7  0.4
6    4.6  3.4  1.4  0.3
7    5.0  3.4  1.5  0.2
8    4.4  2.9  1.4  0.2
9    4.9  3.1  1.5  0.1
10   5.4  3.7  1.5  0.2
11   4.8  3.4  1.6  0.2
12   4.8  3.0  1.4  0.1
13   4.3  3.0  1.1  0.1
14   5.8  4.0  1.2  0.2
15   5.7  4.4  1.5  0.4
16   5.4  3.9  1.3  0.4
17   5.1  3.5  1.4  0.3
18   5.7  3.8  1.7  0.3
19   5.1  3.8  1.5  0.3
20   5.4  3.4  1.7  0.2
21   5.1  3.7  1.5  0.4
22   4.6  3.6  1.0  0.2
23   5.1  3.3  1.7  0.5
24   4.8  3.4  1.9  0.2
25   5.0  3.0  1.6  0.2
26   5.0  3.4  1.6  0.4
27   5.2  3.5  1.5  0.2
28   5.2  3.4  1.4  0.2
29   4.7  3.2  1.6  0.2
30   4.8  3.1  1.6  0.2
31   5.4  3.4  1.5  0.4
32   5.2  4.1  1.5  0.1
33   5.5  4.2  1.4  0.2
34   4.9  3.1  1.5  0.1
35   5.0  3.2  1.2  0.2
36   5.5  3.5  1.3  0.2
37   4.9  3.1  1.5  0.1
38   4.4  3.0  1.3  0.2
39   5.1  3.4  1.5  0.2
40   5.0  3.5  1

In [ ]:
# Write a Pandas function to find the correlation between the first two columns.


In [17]:
first = df.iloc[:, 0]
second = df.iloc[:, 1]

correlation = first.corr(second)
print(correlation)

-0.10936924995064937


In [ ]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.


In [8]:
third = df.iloc[:, 2]

mean = third.mean()
median = third.median()
std = third.std()

print(f"Mean: {mean}\nMedian: {median}\nStandard Deviation: {std}")

Mean: 3.758666666666666
Median: 4.35
Standard Deviation: 1.7644204199522617


In [ ]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column

In [14]:
import math

In [21]:

np.expand_dims(iris_2d,axis=0)
#taking first as petallength and second as sepal length
df[4]=((math.pi * first * second**2)/3)
print(df)

       0    1    2    3          4
0    5.1  3.5  1.4  0.2  65.423667
1    4.9  3.0  1.4  0.2  46.181412
2    4.7  3.2  1.3  0.2  50.399524
3    4.6  3.1  1.5  0.2  46.292415
4    5.0  3.6  1.4  0.2  67.858401
..   ...  ...  ...  ...        ...
145  6.7  3.0  5.2  2.3  63.146012
146  6.3  2.5  5.0  1.9  41.233404
147  6.5  3.0  5.2  2.0  61.261057
148  6.2  3.4  5.4  2.3  75.054743
149  5.9  3.0  5.1  1.8  55.606190

[150 rows x 5 columns]


# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [26]:
 x = np.ones(4, dtype=np.int64)
 print(x)


[1 1 1 1]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [29]:
x = np.arange(1,10)
print(np.split(x,[4,6]))

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [37]:
x = np.random.randint(0,10,(2,5))
print(x)
print(f"MAX: {np.max(x,axis=1)}")
print(f"INDI: {np.argmax(x,axis=1)}\n")

print(f"MAX: {np.min(x,axis=1)}")
print(f"INDI: {np.argmin(x,axis=1)}")



[[8 7 8 5 1]
 [8 3 3 3 5]]
MAX: [8 8]
INDI: [0 0]

MAX: [1 3]
INDI: [4 1]


### Pandas

Run the following load command and solve the following questions

In [39]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [44]:
def unique_count(df,column):
  return df[column].nunique()

df = pd.DataFrame(iris,columns=names)
print(unique_count(df,"species"))

3


# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [67]:
size = []
float_arr = df["petallength"].astype(float)

for i in float_arr:
    if (i) < 3:
        size.append("small")
    elif 3 <= i <= 5:
        size.append("medium")
    else:
        size.append("large")


size = np.array(size)
df["size"] = size
print(df)

    sepallength sepalwidth petallength petalwidth            species    size
0        b'5.1'     b'3.5'      b'1.4'     b'0.2'     b'Iris-setosa'   small
1        b'4.9'     b'3.0'      b'1.4'     b'0.2'     b'Iris-setosa'   small
2        b'4.7'     b'3.2'      b'1.3'     b'0.2'     b'Iris-setosa'   small
3        b'4.6'     b'3.1'      b'1.5'     b'0.2'     b'Iris-setosa'   small
4        b'5.0'     b'3.6'      b'1.4'     b'0.2'     b'Iris-setosa'   small
..          ...        ...         ...        ...                ...     ...
145      b'6.7'     b'3.0'      b'5.2'     b'2.3'  b'Iris-virginica'   large
146      b'6.3'     b'2.5'      b'5.0'     b'1.9'  b'Iris-virginica'  medium
147      b'6.5'     b'3.0'      b'5.2'     b'2.0'  b'Iris-virginica'   large
148      b'6.2'     b'3.4'      b'5.4'     b'2.3'  b'Iris-virginica'   large
149      b'5.9'     b'3.0'      b'5.1'     b'1.8'  b'Iris-virginica'   large

[150 rows x 6 columns]


Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [47]:
def most_freq(df,column):
  return df[column].mode(0)

print(most_freq(df,"petallength"))

0    b'1.5'
Name: petallength, dtype: object
